name: API Test with Newman  # Tên workflow

on:  # Khi nào workflow chạy?
  push:  # Khi có code mới push lên
    branches:
      - main  # Chạy trên nhánh main
  pull_request:  # Khi có pull request vào main
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      - name: Checkout repository  # Bước 1: Clone code về máy ảo runner
        uses: actions/checkout@v3

      - name: Install Node.js  # Bước 2: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman  # Bước 3: Cài đặt Newman và HTML reporter
        run: npm install -g newman newman-reporter-html

      - name: Run API tests  # Bước 4: Chạy kiểm thử API
        run: |
          newman run Upload File API.postman_collection.json \
                     API documentation.postman_collection.json \
          --reporters cli,json,html \
          --reporter-json-export newman-report.json \
          --reporter-html-export newman-report.html

      - name: Upload Test Report  # Bước 5: Upload báo cáo lên GitHub
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-report
          path: newman-report.html
